#!/bin/bash

#
if [ $# -eq 0 ]; then
  #show usage
  $0 usage
fi
CMD=""
#while [ -n "$1" ] ; do
while [ -z "$CMD" ] ; do
  case $1 in
    -r|repo|reposiroty)
      shift
      case $1 in 
        i|info)
          shift
          CMD=repository-info
          ;;
        u|update)
          shift
          CMD=repository-update
          ;;
        *) $0 usage
          ;;
      esac
      shift $#
      ;;
    -ri|-rinfo|repository-info)
      shift
      CMD=repository-info
      shift $#
      ;;
    -ru|-rupdate|repository-update)
      shift
      CMD=repository-update
      shift $#
      ;;
    -p|pkg|package)
      shift
      case $1 in 
        i|install)
          shift
          CMD=package-install
          ;;
        r|remove)
          shift
          CMD=package-remove
          ;;
        s|search)
          shift
          CMD=package-search
          ;;
        sf|search-file)
          shift
          CMD=package-search-file
          ;;
        d|des|description)
          shift
          CMD=package-description
          ;;
        n|need|needed)
          shift
          CMD=package-needed
          ;;
        u|up|upgrade)
          shift
          CMD=package-upgrade
          ;;
        m|mirror)
          shift
          CMD=package-upgrade
          ;;
        *) $0 usage
          ;;
      esac
      #shift $#
      ;;
    -pi|package-install)
      shift
      CMD=package-install
      ;;
    -pr|package-remove) 
      shift
      CMD=package-remove
      ;;
    -ps|package-search) 
      shift
      CMD=package-search
      ;;
    -psf|package-search-file) 
      shift
      CMD=package-search-file
      ;;
    -pd|package-description) 
      shift
      CMD=package-description
      ;;
    -pn|package-needed) 
      shift
      CMD=package-needed
      ;;
    -pu|package-upgrade) 
      shift
      CMD=package-upgrade
      ;;
    -pm|package-mirror) 
      shift
      CMD=package-mirror
      ;;
    *)
    echo "Usage:"
    echo "      $0 : {-r|repo|reposiroty} {i|info u|update}"
    echo "      $0 : {-p|pkg|package} {i|install r|remove s|search sf|search-file}"
    echo "      $0 :                  {d|description n|needed u|up|upgrade m|mirror}"
    exit 0
    ;;

  esac
done


# Case with the comamnds
case "$CMD" in
  repository-info)
    pwd
    ./sbpkg-repository info
    ;;
  repository-update)
    ./sbpkg-repository update
    ;;
  package-install)
    ./sbpkg-package install $@
    ;;
  package-remove)
    ./sbpkg-package remove $@
    ;;
  package-search)
    ./sbpkg-package search $@
    ;;
  package-seach-file)
    ./sbpkg-package search-file $@ 
    ;;
  package-description)
    ./sbpkg-package description $@ 
    ;;
  package-needed)
    ./sbpkg-package needed $@ 
    ;;
  package-upgrade)
    ./sbpkg-package upgrade $@ 
    ;;
  package-mirror)
    ./sbpkg-package mirror $@ 
    ;;
esac
