#!/bin/bash
#
## Copyright (c) 2024 VielLosero 
#
# This file is part of sbpkg. 
# sbpkg is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, 
# or (at your option) any later version.
#
# sbpkg is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with sbpkg. If not, see <https://www.gnu.org/licenses/>. 
#
## sbpkg, - A package manager for slackbuilds.



while [ -n "$1" ] ; do
  case $1 in  
    install)
      shift
      ;;
    remove)
      shift
      ;;
    search)
      shift
      SEARCHLIST=$@
      echo "Searching for $SEARCHLIST"
      ;;
    search-file)
      shift
      ;;
    description)
      shift
      ;;
    needed)
      shift
      ;;
    upgrade)
      shift
      ;;
    mirror)
      shift
      ;;
    *)
      echo "USAGE:"
      echo "      $0 : "
      exit 0
      ;;
  esac
done


