#!/bin/bash
#
## Copyright (c) 2024 VielLosero 
#
# This file is part of sbpkg. 
# sbpkg is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, 
# or (at your option) any later version.
#
# sbpkg is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with sbpkg. If not, see <https://www.gnu.org/licenses/>. 
#
## sbpkg, - A simple package manager for slackbuilds.

source /usr/libexec/sbpkg/sbpkg.functions.sh

findpackage(){
#grep -n "${1}.SlackBuild" /var/lib/sbpkg/sbo/15.0/CHECKSUMS.md5
grep -n "\/${1}.*.SlackBuild" /var/lib/sbpkg/sbo/15.0/CHECKSUMS.md5

}


while [ -n "$1" ] ; do
  case $1 in  
    install)
      shift
      ;;
    remove)
      shift
      ;;
    search)
      shift
      SEARCHLIST=$@
      #echo "Searching for $SEARCHLIST"
      shift $#
      gettags
      for TAG in $REPO_TAGS ; do  
        getrepo
        for PACKAGE in $SEARCHLIST ; do
          FILEPATH=$(grep "SlackBuild$"  ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5 | \
            sed 's:.*/::' | grep "^${PACKAGE}.*.SlackBuild$" | cut -d. -f1)
          [ -z "$FILEPATH" ] && break
          echo "$FILEPATH" | sed "s/.*/${TAG}: &/"
        done
      done
      ;;
    search-file)
      shift
      ;;
    description)
      shift
      DESCLIST=$@
      #echo "Description for $DESCLIST"
      shift $#
      gettags
      for TAG in $REPO_TAGS ; do  
        getrepo
        for PACKAGE in $DESCLIST ; do
          #grep -n ".*${PACKAGE}.*.slack-desc" ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5
          # sanity check, add  | head -1
          #grep -n "${PACKAGE}.slack-desc" ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5 | head -1
          #grep -n "${PACKAGE}.slack-desc" ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5 | head -1 | cut -d " " -f3
          FILEPATH=$(grep -n "\/${PACKAGE}.slack-desc" ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5 | head -1 | cut -d " " -f3)
          [ -z "$FILEPATH" ] && break
          FILE="${REPO_DB}/${REPO_VERSION}/${FILEPATH}"
          #echo $FILE
          if [ -e $FILE ] ; then 
            cat "${REPO_DB}/${REPO_VERSION}/${FILEPATH}" | tail +9
          else
            # if no find on db try to download and show
            case $SOURCE_TYPE in
             file)
               SOURCE="$(echo $REPO_SOURCE | sed 's%file://%%')"
               ;;
             http|https)
               SOURCE=$(echo $REPO_SOURCE)
               #wget file on db and cat it
               ;;
             ftp)
               SOURCE=$(echo $REPO_SOURCE | sed 's%file://%%')
               ;;
             rsync)
               SOURCE="$(echo $REPO_SOURCE)"
               ;;
             git)
               SOURCE=$(echo $REPO_SOURCE | sed 's%file://%%')
               ;;
            esac
          fi
        done
      done
      ;;
    needed)
      shift
      ;;
    upgrade)
      shift
      ;;
    mirror)
      shift
      ;;
    locate)
      shift
      SEARCHLIST=$@
      #echo "Searching for $SEARCHLIST"
      shift $#
      gettags
      for TAG in $REPO_TAGS ; do  
        getrepo
        for PACKAGE in $SEARCHLIST ; do
          FILEPATH=$(grep "SlackBuild$"  ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5 | \
            cut -d. -f2- |sed 's/^\s*.//g'| grep "/${PACKAGE}.*.SlackBuild$" | cut -d. -f1)
          [ -z "$FILEPATH" ] && break
          echo "$FILEPATH" | sed "s/.*/${TAG}: &/"
        done
      done
      ;;
    *)
      echo "USAGE:"
      echo "      $0 : "
      exit 0
      ;;
  esac
done



