#!/bin/bash
#
## Copyright (c) 2024 VielLosero 
#
# This file is part of srpm. 
# srpm is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, 
# or (at your option) any later version.
#
# srpm is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with srpm. If not, see <https://www.gnu.org/licenses/>. 
#
## srpm, - A simple package manager for slackbuilds.

source /usr/libexec/srpm/srpm.functions.sh

findpackage(){
#grep -n "${1}.SlackBuild" /var/lib/srpm/sbo/15.0/CHECKSUMS.md5
grep -n "\/${1}.*.SlackBuild" /var/lib/srpm/sbo/15.0/CHECKSUMS.md5

}


while [ -n "$1" ] ; do
  case $1 in  
    install)
      shift
      ;;
    remove)
      shift
      ;;
    search)
      shift
      SEARCHLIST=$@
      #echo "Searching for $SEARCHLIST"
      shift $#
      gettags_from_config_file
      for TAG in $REPO_TAGS ; do  
        getrepo_vars
        for PACKAGE in $SEARCHLIST ; do
          FILEPATH=$(grep "SlackBuild$"  ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5 | \
            sed 's:.*/::' | grep "^${PACKAGE}.*.SlackBuild$" | cut -d. -f1)
          if [ -n "$FILEPATH" ] ; then
            echo "$FILEPATH" | sed "s/.*/${TAG}: &/"
          fi
        done
      done
      ;;
    search-file)
      shift
      ;;
    description)
      shift
      DESCLIST=$@
      #echo "Description for $DESCLIST"
      shift $#
      gettags_from_config_file
      for TAG in $REPO_TAGS ; do  
        getrepo_vars
        for PACKAGE in $DESCLIST ; do
          #grep -n ".*${PACKAGE}.*.slack-desc" ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5
          # sanity check, add  | head -1
          #grep -n "${PACKAGE}.slack-desc" ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5 | head -1
          #grep -n "${PACKAGE}.slack-desc" ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5 | head -1 | cut -d " " -f3
          FILEPATH=$(grep -n "\/${PACKAGE}.slack-desc" ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5 | head -1 | cut -d " " -f3)
          if [ -n "$FILEPATH" ] ; then
            FILE="${REPO_DB}/${REPO_VERSION}/${FILEPATH}"
            #echo $FILE
            if [ -e $FILE ] ; then 
              cat "${REPO_DB}/${REPO_VERSION}/${FILEPATH}" | tail +9
            else
              # if no find on db try to download and show
              case $SOURCE_TYPE in
               file)
                 SOURCE="$(echo $REPO_SOURCE | sed 's%file://%%')"
                 ;;
               http|https)
                 SOURCE=$(echo $REPO_SOURCE)
                 #wget file on db and cat it
                 ;;
               ftp)
                 SOURCE=$(echo $REPO_SOURCE | sed 's%file://%%')
                 ;;
               rsync)
                 SOURCE="$(echo $REPO_SOURCE)"
                 ;;
               git)
                 SOURCE=$(echo $REPO_SOURCE | sed 's%file://%%')
                 ;;
              esac
            fi
          fi
        done
      done
      ;;
    needed)
      shift
      ;;
    upgrade)
      shift
      ;;
    mirror)
      shift
      ;;
    locate)
      shift
      SEARCHLIST=$@
      #echo "Searching for $SEARCHLIST"
      shift $#
      gettags_from_config_file
      for TAG in $REPO_TAGS ; do  
        getrepo_vars
        for PACKAGE in $SEARCHLIST ; do
          FILEPATH=$(grep "SlackBuild$"  ${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5 | \
            cut -d. -f2- |sed 's/^\s*.//g'| grep "/${PACKAGE}.*.SlackBuild$" | cut -d. -f1 | \
            rev | cut -d/ -f2- | rev)
          if [ -n "$FILEPATH" ] ; then
            #echo "$FILEPATH" | sed "s;.*;${TAG}: ${REPO_SOURCE}/&;"
            echo "$FILEPATH" | sed "s;.*;${TAG}: &;"
          fi
        done
      done
      ;;
    *)
      echo "USAGE:"
      echo "      $0 : "
      exit 0
      ;;
  esac
done



