#!/bin/bash
#
## Copyright (c) 2024 VielLosero 
#
# The program is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, 
# or (at your option) any later version.
#
# The program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <https://www.gnu.org/licenses/>. 
#
## srpm, - A simple repository & package manager for Slackware Linux.

# version
VERSION=0.1.8

# Check if pkg db is started.
if [ -z "$(ls -A /var/lib/srpm)" ] ; then
  echo "DB empty"
fi
# Check if pkg db is up to date.

# Now process args.
CMD=""
while [ -z "$CMD" ] ; do
  case $1 in
    -r|repo|reposiroty)
      shift
      case $1 in 
        i|info)
          shift
          CMD=repository-info
          ;;
        u|update)
          shift
          CMD=repository-update
          ;;
        c|check)
          shift
          CMD=repository-check
          ;;
      esac
      shift $#
      ;;
    -ri|-rinfo|repository-info)
      shift
      CMD=repository-info
      shift $#
      ;;
    -ru|-rupdate|repository-update)
      shift
      CMD=repository-update
      shift $#
      ;;
    -rc|-rcheck|repository-check)
      shift
      CMD=repository-check
      shift $#
      ;;
    -p|pkg|package)
      shift
      case $1 in 
        i|install)
          shift
          CMD=package-install
          ;;
        r|remove)
          shift
          CMD=package-remove
          ;;
        s|search)
          shift
          CMD=package-search
          ;;
        sf|search-file)
          shift
          CMD=package-search-file
          ;;
        d|des|description)
          shift
          CMD=package-description
          ;;
        n|need|needed)
          shift
          CMD=package-needed
          ;;
        u|up|upgrade)
          shift
          CMD=package-upgrade
          ;;
        m|mirror)
          shift
          CMD=package-upgrade
          ;;
      esac
      #shift $#
      ;;
    -pi|package-install)
      shift
      CMD=package-install
      ;;
    -pr|package-remove) 
      shift
      CMD=package-remove
      ;;
    -ps|package-search) 
      shift
      CMD=package-search
      ;;
    -psf|package-search-file) 
      shift
      CMD=package-search-file
      ;;
    -pd|package-description) 
      shift
      CMD=package-description
      ;;
    -pn|package-needed) 
      shift
      CMD=package-needed
      ;;
    -pu|package-upgrade) 
      shift
      CMD=package-upgrade
      ;;
    -pm|package-mirror) 
      shift
      CMD=package-mirror
      ;;
    -v|ver|version)
      shift
       #CMD=version
      echo ""
      echo "$0 - version $VERSION"
      ;;
    *)
      #CMD=NULL
      echo ""
      echo "Usage:"
      echo "      $0 : {-r|repo|reposiroty} {i|info u|update c|check}"
      echo "      $0 : {-p|pkg|package} {i|install r|remove s|search}"
      echo "      $0 :                  {d|description sf|search-file}"
      echo "      $0 :                  {n|needed u|up|upgrade m|mirror}"
      echo "      $0 : {-v|version}"
      exit 0
    ;;

  esac
done


# Case with comamnd
case "$CMD" in
  repository-info)
    /usr/libexec/srpm/srpm-repository info
    ;;
  repository-update)
    /usr/libexec/srpm/srpm-repository update
    ;;
  repository-check)
    /usr/libexec/srpm/srpm-repository check
    ;;
  package-install)
    /usr/libexec/srpm/srpm-package install $@
    ;;
  package-remove)
    /usr/libexec/srpm/srpm-package remove $@
    ;;
  package-search)
    /usr/libexec/srpm/srpm-package search $@
    ;;
  package-seach-file)
    /usr/libexec/srpm/srpm-package search-file $@ 
    ;;
  package-description)
    /usr/libexec/srpm/srpm-package description $@ 
    ;;
  package-needed)
    /usr/libexec/srpm/srpm-package needed $@ 
    ;;
  package-upgrade)
    /usr/libexec/srpm/srpm-package upgrade $@ 
    ;;
  package-mirror)
    /usr/libexec/srpm/srpm-package mirror $@ 
    ;;
esac
