#!/bin/bash
#
## Copyright (c) 2024 VielLosero 
#
# This file is part of srpm. 
# srpm is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, 
# or (at your option) any later version.
#
# srpm is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with srpm. If not, see <https://www.gnu.org/licenses/>. 
#
## srpm, - A simple repository & package manager for slackbuilds.

source /usr/libexec/srpm/srpm.functions.sh

#REPO_CONFIG_FILE=/etc/srpm/srpm.repositories
TMPDIR=${TMPDIR:-/tmp/srpm} && [[ -d $TMPDIR ]] || mkdir -vp $TMPDIR

## # Get all diferent tags from repositories in repo config file
## # A  tag is like the repository name
## gettags_from_config_file(){
## REPO_TAGS=$(cat $REPO_CONFIG_FILE | grep "^REPO_" | cut -d_ -f2 | sort -u)
## }
## 
## getrepo_vars(){
##   REPO_NAME=$(cat $REPO_CONFIG_FILE | grep "^REPO_${TAG}_NAME" | cut -d= -f2 | tr -d '"')
##   REPO_VERSION=$(cat $REPO_CONFIG_FILE | grep "^REPO_${TAG}_VERSION" | cut -d= -f2 | tr -d '"')
##   REPO_DB="$(cat $REPO_CONFIG_FILE | grep "^REPO_${TAG}_DBDIR" | cut -d= -f2 | tr -d '"')/${REPO_NAME}"
##   # activate pkg db by make repo dir 
##   [[ ! -d ${REPO_DB} ]] && mkdir -vp ${REPO_DB}
##   REPO_SOURCE=$(cat $REPO_CONFIG_FILE | grep "^REPO_${TAG}_SOURCE" | cut -d= -f2 | tr -d '"')
##   SOURCE_TYPE="$(echo $REPO_SOURCE | cut -d: -f1 )"
##   REPO_UPDATE=$(cat $REPO_CONFIG_FILE | grep "^REPO_${TAG}_UPDATE" | cut -d= -f2 | tr -d '"')
##   # sanity check if no UPDATE on config take SOURCE
##   if [ -z $REPO_UPDATE ] ; then
##     REPO_UPDATE=$REPO_SOURCE
##   fi
##   echo "Get files from: $REPO_UPDATE"
##   UPDATE_TYPE="$(echo $REPO_UPDATE | cut -d: -f1 )"
## }

info(){
#get repos (tags) from repo config file 
#REPO_TAGS=$(cat $REPO_CONFIG_FILE | grep "^REPO_" | cut -d_ -f2 | sort -u)
gettags_from_config_file
#clear
echo "------------------------"
echo "- Repository information"
echo "------------------------"
for TAG in $REPO_TAGS ; do  
  cat $REPO_CONFIG_FILE | grep "^REPO_${TAG}"
  echo "------------------------"
done
}

check(){
#get repos (tags) from repo config file 
#REPO_TAGS=$(cat $REPO_CONFIG_FILE | grep "^REPO_" | cut -d_ -f2 | sort -u)
gettags_from_config_file
#clear
  echo "------------------------"
  echo "- Repository up to date"
  echo "------------------------"
for TAG in $REPO_TAGS ; do  
  getrepo_vars 
  mkdir -vp ${TMPDIR}/${REPO_NAME}
  case $UPDATE_TYPE in
    file)
      SOURCE="$(echo $REPO_SOURCE | sed 's%file://%%')"
      cp ${SOURCE}/ChangeLog.txt ${TMPDIR}/${REPO_NAME}/ChangeLog.txt
      cp ${SOURCE}/CHECKSUMS.md5 ${TMPDIR}/${REPO_NAME}/CHECKSUMS.md5
      cp ${SOURCE}/CHECKSUMS.md5.asc ${TMPDIR}/${REPO_NAME}/CHECKSUMS.md5.asc
      get_Changelog_date_and_packages_number
      #SOURCE_UPDATED="$(cat ${TMPDIR}/${REPO_NAME}/ChangeLog.txt  | head -1)"
      #SOURCE_PKGS="$(grep slack-desc ${TMPDIR}/${REPO_NAME}/CHECKSUMS.md5 | wc -l )"     
      ;;
    http|https)
      SOURCE=$(echo $REPO_SOURCE)
      wget -O ${TMPDIR}/${REPO_NAME}  ${SOURCE}/ChangeLog.txt
      wget -O ${TMPDIR}/${REPO_NAME}  ${SOURCE}/CHECKSUM.md5
      wget -O ${TMPDIR}/${REPO_NAME}  ${SOURCE}/CHECKSUM.md5.asc
      get_Changelog_date_and_packages_number
      #SOURCE_UPDATED="$(curl --connect-timeout 6 -s ${SOURCE}/ChangeLog.txt | head -n1  || echo fail )"
      #SOURCE_PKGS="$(curl --connect-timeout 6 -s ${SOURCE}/CHECKSUMS.md5 | grep slack-desc | wc -l || echo fail)"     
      ;;
    ftp)
      SOURCE=$(echo $REPO_SOURCE | sed 's%file://%%')
      ;;
    rsync)
      rsync -aqP ${REPO_UPDATE}/ChangeLog.txt ${REPO_UPDATE}/CHECKSUMS.md5 ${REPO_UPDATE}/CHECKSUMS.md5.asc ${TMPDIR}/${REPO_NAME}/
      get_Changelog_date_and_packages_number
      #SOURCE_UPDATED="$(cat ${TMPDIR}/${REPO_NAME}/ChangeLog.txt  | head -1)"
      #SOURCE_PKGS="$(grep slack-desc ${TMPDIR}/${REPO_NAME}/CHECKSUMS.md5 | wc -l )"     
      ;;
    git)
      SOURCE=$(echo $REPO_SOURCE | sed 's%file://%%')
      ;;
  esac
  # check date on db
  DB_UPDATED=$( cat ${REPO_DB}/${REPO_VERSION}/ChangeLog.txt  | head -1)
  
  #echo "SOURCE: $SOURCE"
  #cat $REPO_CONFIG_FILE | grep "^REPO_${TAG}"
  echo "NAme:          \"$REPO_NAME\""
  echo "Source date:   \"$SOURCE_UPDATED\""
  echo "Local db date: \"$DB_UPDATED\""
  #gpg --verify  ${TMPDIR}/${REPO_NAME}/CHECKSUMS.md5.asc > /dev/null || echo "### WARNING: gpg BAD signature. ###"
  gpg --verify  ${TMPDIR}/${REPO_NAME}/CHECKSUMS.md5.asc &> /dev/null || \
    cat <<"EOF"
  ###################################
  ### WARNING: BAD gpg signature. ###
  ###################################
EOF
  echo "------------------------"
  #echo "SOURCE_${TAG}_PKGS=\"$REPO_PKGS\""
done
}

update(){
echo ""
#get repos (tags) from repo config file 
#REPO_TAGS=$(cat $REPO_CONFIG_FILE | grep "^REPO_" | cut -d_ -f2 | sort -u)
gettags_from_config_file
for TAG in $REPO_TAGS ; do  
  # get repo var
  getrepo_vars
  case $UPDATE_TYPE in
    http|https)
      SOURCE=$(echo $REPO_UPDATE)
      wget -O ${REPO_DB}/${REPO_VERSION}  ${SOURCE}/ChangeLog.txt
      wget -O ${REPO_DB}/${REPO_VERSION}  ${SOURCE}/CHECKSUMS.md5
      wget -O ${REPO_DB}/${REPO_VERSION}  ${SOURCE}/CHECKSUMS.md5.asc
      ;;
    ftp)
      echo $REPO_UPDATE
      SOURCE=$(echo $REPO_UPDATE | sed 's%file:/%%')
      ;;
    rsync)
      case "$SOURCE_TYPE" in
        file)
          LOCAL_MIRROR=$(echo $REPO_SOURCE | sed 's%file://%%')
          echo "rsync -avP ${REPO_UPDATE}/ ${LOCAL_MIRROR}/" 
          rsync -avP ${REPO_UPDATE}/ ${LOCAL_MIRROR}/ 
          if [ -L ${REPO_DB}/${REPO_VERSION} ] ; then
            true
          else
            # create a symlink from mirror to db
            ln -s ${LOCAL_MIRROR} ${REPO_DB}/${REPO_VERSION}
          fi
          ;;
        rsync)
          cat <<"EOF"
          rsync -avP ${REPO_UPDATE}/ChangeLog.txt \
                     ${REPO_UPDATE}/CHECKSUMS.md5 \
                     ${REPO_UPDATE}/CHECKSUMS.md5.asc \
                     ${REPO_DB}/${REPO_VERSION}"
EOF
          ;;
      esac
      ;;
    git)
      echo $REPO_UPDATE
      SOURCE=$(echo $REPO_UPDATE | sed 's%file:/%%')
      ;;
  esac
  
  #  after update verify signature
  gpg --verify "${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5.asc" "${REPO_DB}/${REPO_VERSION}/CHECKSUMS.md5"
  #check md5sum of ChangeLog.txt
  #tail +13 CHECKSUMS.md5 | md5sum -c --quiet -


done
}

#recreate packages versions on db.
versions(){ 
gettags_from_config_file
for TAG in $REPO_TAGS ; do  
  getrepo_vars
  echo ""
  make_packages_version_db $TAG
  make_packages_requires_db $TAG
done
}

while [ -n "$1" ] ; do
  case $1 in  
    info)
      shift
      info
      ;;
    check)
      shift
      check
      ;;
    update)
      shift
      update
      ;;
    versions)
      shift
      versions
      ;;
    select)
      ;;
    clean-db)
      ;;
    *)
      echo "USAGE:"
      echo "      $0 : "
      shift $#
      ;;
  esac
done

# vim:sw=2:ts=2:et:
