#!/bin/bash
#
## Copyright (c) 2024 VielLosero 
#
# The program is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, 
# or (at your option) any later version.
#
# The program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <https://www.gnu.org/licenses/>. 
#
## srpm, - A simple repository & package manager for Slackware Linux.

# version
VERSION=0.1.15

# Check if pkg db is started.
if [ -z "$(ls -A /var/lib/srpm)" ] ; then
  echo "DB empty"
fi
# Check if pkg db is up to date.

# Now process args.
CMD=""
while [ -z "$CMD" ] ; do
  case $1 in
    -r|repo|reposiroty)
      shift
      case $1 in 
        i|info)
          shift
          CMD=repository-info
          ;;
        u|update)
          shift
          CMD=repository-update
          ;;
        c|check)
          shift
          CMD=repository-check
          ;;
        v|versions)
          shift
          CMD=repository-versions
          ;;
      esac
      shift $#
      ;;
    -ri|-rinfo|repository-info)
      shift
      CMD=repository-info
      shift $#
      ;;
    -ru|-rupdate|repository-update)
      shift
      CMD=repository-update
      shift $#
      ;;
    -rc|-rcheck|repository-check)
      shift
      CMD=repository-check
      shift $#
      ;;
    -rv|-rversions|repository-versions)
      shift
      CMD=repository-versions
      shift $#
      ;;
    -p|pkg|package)
      shift
      case $1 in 
        i|install)
          shift
          CMD=package-install
          ;;
        r|remove)
          shift
          CMD=package-remove
          ;;
        s|search)
          shift
          CMD=package-search
          ;;
        sf|search-file)
          shift
          CMD=package-search-file
          ;;
        d|des|description)
          shift
          CMD=package-description
          ;;
        n|need|needed)
          shift
          CMD=package-needed
          ;;
        u|up|unattended)
          shift
          CMD=package-unattended
          ;;
        m|mirror)
          shift
          CMD=package-mirror
          ;;
        l|locate)
          shift
          CMD=package-locate
          ;;
        v|version)
          shift
          CMD=package-version
          ;;
        f|forced)
          shift
          CMD=package-forced
          ;;
      esac
      #shift $#
      ;;
    -pi|package-install)
      shift
      CMD=package-install
      ;;
    -pr|package-remove) 
      shift
      CMD=package-remove
      ;;
    -ps|package-search) 
      shift
      CMD=package-search
      ;;
    -psf|package-search-file) 
      shift
      CMD=package-search-file
      ;;
    -pd|package-description) 
      shift
      CMD=package-description
      ;;
    -pn|package-needed) 
      shift
      CMD=package-needed
      ;;
    -pnv|package-needed-version) 
      shift
      CMD=package-needed-version
      ;;
    -pu|package-unattended) 
      shift
      CMD=package-unattended
      ;;
    -pm|package-mirror) 
      shift
      CMD=package-mirror
      ;;
    -pl|package-locate) 
      shift
      CMD=package-locate
      ;;
    -pv|package-version) 
      shift
      CMD=package-version
      ;;
    -pf|package-forced) 
      shift
      CMD=package-forced
      ;;
    -v|ver|version)
      shift
       #CMD=version
      echo ""
      echo "$0 - version $VERSION"
      ;;
    *)
      #CMD=NULL
      echo ""
      echo "Usage:"
      echo "      $(basename $0) {-r|repo|reposiroty} {i|info c|check u|update v|versions}"
      echo "      $(basename $0) {-p|pkg|package} {i|install r|remove s|search}"
      echo "      $(basename $0)                  {d|description sf|search-file}"
      echo "      $(basename $0)                  {n|needed u|unattended m|mirror}"
      echo "      $(basename $0)                  {l|locate v|version f|forced} PATTERN|PACKAGE"
      echo "      $(basename $0) {-v|version}"
      exit 0
    ;;

  esac
done


# Case with comamnd
case "$CMD" in
  repository-info)
    /usr/libexec/srpm/srpm-repository info
    ;;
  repository-update)
    /usr/libexec/srpm/srpm-repository update
    ;;
  repository-check)
    /usr/libexec/srpm/srpm-repository check
    ;;
  repository-versions)
    /usr/libexec/srpm/srpm-repository versions
    ;;
  package-install)
    /usr/libexec/srpm/srpm-package install $@
    ;;
  package-remove)
    /usr/libexec/srpm/srpm-package remove $@
    ;;
  package-search)
    /usr/libexec/srpm/srpm-package search $@
    ;;
  package-seach-file)
    /usr/libexec/srpm/srpm-package search-file $@ 
    ;;
  package-description)
    /usr/libexec/srpm/srpm-package description $@ 
    ;;
  package-needed)
    /usr/libexec/srpm/srpm-package needed $@ 
    ;;
  package-needed-version)
    $(basename $0) -pv $($(basename $0) -pn $@ | cut -d: -f1 | tac | awk '!_[$0]++' | tr  "\n" " ")
    ;;
  package-unattended)
    /usr/libexec/srpm/srpm-package unattended $@ 
    ;;
  package-mirror)
    /usr/libexec/srpm/srpm-package mirror $@ 
    ;;
  package-locate)
    /usr/libexec/srpm/srpm-package locate $@ 
    ;;
  package-version)
    /usr/libexec/srpm/srpm-package version $@ 
    ;;
  package-forced)
    /usr/libexec/srpm/srpm-package forced $@ 
    ;;
esac

# vim:sw=2:ts=2:et:
